In [ ]:
import numpy as np
np.__version__

# Create an 1d array useing array function

In [6]:
a =np.array([1,2,3,4,5])
print(a)
print(a.shape)
print(a.dtype)

[1 2 3 4 5]
(5,)
int32


# Create an 2d array useing array function

In [7]:
a =np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(a.shape)
print(a.dtype)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
int32


# Create an 3d array useing array function

In [10]:
a =np.array([[[1,2,3],[2,3,4]],[[3,4,5],[4,5,6]],[[5,6,7],[6,7,8]]])
print(a)
print(a.dtype)
print(a.shape)


[[[1 2 3]
  [2 3 4]]

 [[3 4 5]
  [4 5 6]]

 [[5 6 7]
  [6 7 8]]]
int32
(3, 2, 3)


# create 1D array using arange function

In [12]:
b =np.arange(10)
print(b)
print(b.dtype)
print(b.shape)

[0 1 2 3 4 5 6 7 8 9]
int32
(10,)


# create 2D array using arange function

In [17]:
b =np.arange(10).reshape(2,5)
print(b)
print(b.shape)
print(b.dtype)


[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)
int32


# create 3D array using arange function

In [36]:
b =np.arange(18).reshape(3,2,3)
print(b)
print(b.shape)
print(b.dtype)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]
(3, 2, 3)
int32


# create array useing ones 1D

In [54]:
c =np.ones(10,dtype=np.int32)
print(c)
#print(c.dtype)
print(c.shape)

[1 1 1 1 1 1 1 1 1 1]
(10,)


# create array useing ones 2D

In [62]:
c =np.ones(([5,2]))
print(c)
print(c.shape)
print(c.dtype)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
(5, 2)
float64


# create array useing ones 3D

In [65]:
c =np.ones((([5,3,5])))
print(c)
print(c.shape)
print(c.dtype)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(5, 3, 5)
float64


# creating random numbers useing 1D array

In [86]:
d =np.random.randint(1,3,size=(10))
print(d)
print(d.shape)
print(d.dtype)

[1 1 1 2 2 2 2 1 1 2]
(10,)
int32


# creating random numbers useing 2D array

In [93]:
d =np.random.randint(5,10,size=(5,10))
print(d)
print(d.shape)
print(d.dtype)



[[8 6 5 6 5 9 5 6 5 6]
 [7 9 8 8 8 8 7 8 9 8]
 [5 6 6 9 7 5 8 5 5 6]
 [8 5 6 5 6 5 9 8 9 5]
 [6 9 8 7 6 5 9 9 7 6]]
(5, 10)
int32


# creating random numbers useing 3D array

In [106]:
d =np.random.randint(5,10,size=(3,3,3))
print(d)
print(d.shape)
print(d.dtype)

[[[6 6 9]
  [5 8 5]
  [6 8 7]]

 [[7 7 9]
  [5 6 5]
  [6 8 9]]

 [[8 8 9]
  [6 8 9]
  [8 9 5]]]
(3, 3, 3)
int32


# crete array with single low multipal high

In [110]:
e =np.random.randint(5,[10,20,30])
print(e)
print(e.shape)
print(e.dtype)

[ 9  8 11]
(3,)
int32


# crete array with single high multipal low

In [115]:
e =np.random.randint([10,20,30],50)
print(e)
print(e.shape)
print(e.dtype)

[21 24 49]
(3,)
int32


# crete array with  multipal low multipal high

In [119]:
e =np.random.randint([2,4,8],[10,20,30])
print(e)
print(e.shape)
print(e.dtype)


[ 9 13 13]
(3,)
int32


# random.randn function 1D

In [128]:
f =np.random.randn(10)
f

array([-1.07566383,  0.91281642, -0.41425969,  0.07458344,  0.36475059,
        0.41151678,  1.1648124 ,  0.96281939, -0.01190039,  0.21752064])

# random.randn function 2D

In [131]:
f =np.random.randn(5,10)
print(f)
print(f.dtype)
print(f.shape)

[[-0.69718365  1.46297091 -1.29421719  0.35136174  0.47872806 -1.05146324
   0.21103406 -0.37905229 -0.2169517   0.28562658]
 [-0.98412141  1.31422698  0.2656402  -0.73095166  0.82510126 -1.73746647
   0.55399876  0.32860521  1.58821494  0.42488293]
 [ 0.54097532  1.47757289  1.18802402 -0.3614405   0.53378967  0.19769988
  -1.33348782 -1.72552988  0.7933729   0.48489573]
 [ 1.30435152 -1.12992666 -1.48737915 -0.35855257  2.65547088  2.42045471
   2.58675236 -0.6813945  -1.4316016   0.72672441]
 [ 1.82387784 -0.80780769 -0.68182683 -1.44445206 -0.62614631 -1.20836189
  -1.18342884  0.60286689 -0.82581641  0.22268491]]
float64
(5, 10)


# random.randn function 3D

In [135]:
f =np.random.randn(2,4,8)
print(f)
print(f.shape)
print(f.dtype)

[[[ 0.47434025 -1.613174   -0.43304387 -1.57552212 -1.71245814
   -0.14363264  0.29383292 -0.10166969]
  [ 0.45218405  0.32002265  0.39855177 -1.16406866  0.59678873
   -0.21634414 -0.1538594   1.89365452]
  [-3.29428088 -0.16712516 -0.54807568 -0.30377643  0.82929447
   -0.06168004  0.54987585  0.22498544]
  [-0.58417697 -1.72143436 -1.71141287  1.35153854 -0.99970278
   -0.73679984  0.8751589  -1.18743433]]

 [[-0.31209369  1.24764777 -0.77396921 -0.53032037  1.00733451
   -1.18420759 -0.54398873 -0.61977556]
  [-0.8555891  -0.51506896  0.39509161  0.3628351  -2.16442741
   -0.78857654 -0.65063251  0.69615374]
  [-0.74789593  0.4502436   2.38423948  0.61518975  0.06685943
   -1.23512308  0.11427477 -0.99727327]
  [ 0.41660677  0.59070864  0.64306179  1.56993514 -0.95390366
    0.0582889  -0.32853493 -0.21243358]]]
(2, 4, 8)
float64


# creating rand function 1D

In [140]:
g =np.random.rand(10)
print(g)
print(g.shape)
print(g.dtype)

[0.64414871 0.81259784 0.20640097 0.92817078 0.44793233 0.43286562
 0.27739818 0.49751568 0.44733841 0.29595154]
(10,)
float64


# create rand function 2D

In [144]:
g =np.random.rand(5,8)
print(g)
print(g.shape)
print(g.dtype)

[[0.59209358 0.81440626 0.07696993 0.17070308 0.37358458 0.86623814
  0.6729894  0.25448844]
 [0.2639719  0.13645231 0.48264761 0.83944891 0.93855233 0.7067304
  0.11880265 0.20890534]
 [0.74536565 0.75364245 0.60970143 0.04389582 0.77333384 0.68364194
  0.83145371 0.27399696]
 [0.69332441 0.15931609 0.38021146 0.34238876 0.87377085 0.39870708
  0.47009253 0.22194429]
 [0.4258866  0.89594264 0.70689152 0.70157318 0.69489751 0.81854752
  0.75987079 0.58121542]]
(5, 8)
float64


# create rand function 3D

In [147]:
g =np.random.rand(2,4,6)
print(g)
print(g.shape)
print(g.dtype)

[[[0.30443774 0.84995386 0.27517428 0.018529   0.00593678 0.69623245]
  [0.27134834 0.27446917 0.60517864 0.71658105 0.609389   0.59175145]
  [0.11040054 0.60964939 0.69686487 0.96990726 0.39461823 0.39426819]
  [0.08685225 0.42241276 0.28350476 0.0904904  0.14097467 0.01821525]]

 [[0.74966216 0.0969189  0.69578828 0.93649633 0.95585056 0.82756011]
  [0.87387625 0.41430694 0.45017214 0.29415366 0.5155944  0.87271291]
  [0.5854167  0.7264927  0.69019101 0.56874634 0.24801962 0.76931556]
  [0.2362825  0.71684574 0.18832297 0.18866968 0.08738967 0.02844395]]]
(2, 4, 6)
float64


# creating array positive indexing 1D

In [149]:
h =np.array([10,22,33,4,9])
print(h[3])
print(h[0])

4
10


# creating array positive indexing 2D

In [152]:
h =np.array([[1,2,3,4],[5,6,7,8]])
print(h[0,1])
print(h[1,0])

2
5


# creating array positive indexing 3D

In [159]:
h =np.array([[[1,2,3,],[2,3,4]],[[3,4,5],[4,5,6]],[[5,6,7],[6,7,8]]])
print(h[2,0,1])
print(h[2,1,2])
print(h[1,0,2])
print(h[1,1,0])
print(h[0,0,1])
print(h[0,1,0])






6
8
5
4
2
2


# creating array negative indexing 1D

In [161]:
i=np.array([1,2,3,4,5])
print(i[-4])
print(i[-1])

2
5


# creating array negative indexing 2D

In [165]:
i=np.array([[1,2,3,4],[5,6,7,8]])
print(i[-1,-3])
print(i[-2,-1])

6
4


# creating array negative indexing 3D

In [177]:
i=np.array([[[1,2,3],[2,3,4]],[[3,4,5],[4,5,6]],[[5,6,7],[6,7,8]]])
print(i[-1,-1,-1])
print(i[-1,-2,-3])
print(i[-2,-1,-2])
print(i[-2,-2,-3])
print(i[-3,-1,-2])
print(i[-3,-2,-1])

8
5
5
3
3
3


# numpy array slicing

# slice elements from index 1to index 5 from the folling array

In [184]:
j =np.array([1,2,3,4,5,6,7])
print(j[1:5])
print(j[:6])

[2 3 4 5]
[1 2 3 4 5 6]


# slice elements from index 4to end array

In [187]:
j =np.array([1,2,3,4,5,6,7,8])
print(j[4:])
#from index 2to end
print(j[2:])

[5 6 7 8]
[3 4 5 6 7 8]


# slice elements from start to index 4 (not include)

In [189]:
j =np.array([1,2,3,4,5,6,7,8,9,10])
print(j[:4])
#start to index 7
print(j[:7])

[1 2 3 4]
[1 2 3 4 5 6 7]


# negative slicing

# slice from index 3 from end of to index 1 from end

In [191]:
k =np.array([1,2,3,4,5,6,7,8,9])
print(k[-3:-1])
# index 7 to index 3 from end

print(k[-7:-3])

[7 8]
[3 4 5 6]


# return every eliments from index 1 to index 5

In [194]:
k=np.array([1,2,3,4,5])
print(k[:-1])

[1 2 3 4]
